cc_binary(
    name = "hello",
    #    deps = [":hello_lib"],
    srcs = ["hello.cc"],
    copts = [
        "-DHAVE_CONFIG_H",
        "-DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"",
        "-DUNITY_INCLUDE_CONFIG_H",
        "-DWITH_POSIX",
        "-D_GNU_SOURCE",
        "-DIDF_VER=\"v4.4-dev-960-gcf457d412\"",
        "-DESP_PLATFORM",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/config",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/newlib/platform_include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/freertos/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/freertos/port/xtensa/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_hw_support/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_hw_support/include/soc",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_hw_support/port/esp32",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/heap/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/log/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/lwip/include/apps",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/lwip/include/apps/sntp",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/lwip/lwip/src/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/lwip/port/esp32/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/lwip/port/esp32/include/arch",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/soc/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/soc/esp32",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/soc/esp32/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/hal/esp32/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/hal/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_rom/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_rom/esp32",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_common/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_system/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_system/port/soc",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_system/port/public_compat",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp32/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/driver/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/driver/esp32/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_pm/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_ringbuf/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/efuse/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/efuse/esp32/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/xtensa/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/xtensa/esp32/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/vfs/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_wifi/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_wifi/esp32/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_event/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_netif/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_eth/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/tcpip_adapter/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/app_trace/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_timer/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/mbedtls/port/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/mbedtls/mbedtls/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/mbedtls/esp_crt_bundle/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/app_update/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/spi_flash/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/bootloader_support/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_ipc/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/nvs_flash/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/pthread/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_gdbstub/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_gdbstub/xtensa",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_gdbstub/esp32",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/espcoredump/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/espcoredump/include/port/xtensa",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/wpa_supplicant/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/wpa_supplicant/port/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/wpa_supplicant/include/esp_supplicant",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/perfmon/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/asio/asio/asio/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/asio/port/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/bt/common/osi/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/bt/include/esp32/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/bt/host/bluedroid/api/include/api",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/cbor/port/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/unity/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/unity/unity/src",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/cmock/CMock/src",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/coap/port/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/coap/port/include/coap",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/coap/libcoap/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/coap/libcoap/include/coap2",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/console",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/nghttp/port/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/nghttp/nghttp2/lib/includes",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-tls",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-tls/esp-tls-crypto",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_adc_cal/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_hid/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/tcp_transport/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_http_client/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_http_server/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_https_ota/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/protobuf-c/protobuf-c",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/protocomm/include/common",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/protocomm/include/security",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/protocomm/include/transports",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/mdns/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_local_ctrl/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/sdmmc/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_serial_slave_link/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_websocket_client/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/expat/expat/expat/lib",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/expat/port/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/wear_levelling/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/fatfs/diskio",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/fatfs/vfs",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/fatfs/src",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/freemodbus/common/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/idf_test/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/idf_test/include/esp32",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/jsmn/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/json/cJSON",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/libsodium/libsodium/src/libsodium/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/libsodium/port_include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/mqtt/esp-mqtt/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/openssl/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/spiffs/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/ulp/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/wifi_provisioning/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/button/button/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/json_parser",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/json_parser/jsmn/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/json_generator",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_schedule/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_rainmaker/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/qrcode/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/ws2812_led",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_littlefs/src",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp_littlefs/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/dotprod/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/support/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/windows/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/windows/hann/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/windows/blackman/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/windows/blackman_harris/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/windows/blackman_nuttall/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/windows/nuttall/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/windows/flat_top/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/iir/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/fir/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/math/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/math/add/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/math/sub/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/math/mul/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/math/addc/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/math/mulc/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/math/sqrt/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/matrix/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/fft/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/dct/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/conv/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-dsp/modules/common/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-face/face_detection/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-face/face_recognition/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-face/object_detection/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-face/image_util/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-face/pose_estimation/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp-face/lib/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp32-camera/driver/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/esp32-camera/conversions/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/sdk/esp32/include/fb_gfx/include",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/cores/esp32",
        #      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/variants/esp32",
        "-mlongcalls",
        "-Wno-frame-address",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-error=unused-function",
        "-Wno-error=unused-variable",
        "-Wno-error=deprecated-declarations",
        "-Wno-unused-parameter",
        "-Wno-sign-compare",
        "-ggdb",
        "-O2",
        "-fstack-protector",
        "-fstrict-volatile-bitfields",
        "-Wno-error=unused-but-set-variable",
        "-std=gnu++11",
        "-fexceptions",
        "-fno-rtti",
        "-MMD",
        "-c",
        "-DF_CPU=240000000L",
        "-DARDUINO=10607",
        "-DARDUINO_ESP32_DEV",
        "-DARDUINO_ARCH_ESP32",
        "-DARDUINO_BOARD=\"ESP32_DEV\"",
        "-DARDUINO_VARIANT=\"esp32\"",
        "-DESP32",
        "-DCORE_DEBUG_LEVEL=0",
        "-DARDUINO_RUNNING_CORE=1",
        "-DARDUINO_EVENT_RUNNING_CORE=1",
        "-DARDUINO_SERIAL_PORT=0",
    ],
    linkopts = [
    ],
    visibility = ["//visibility:public"],
    deps = ["@esp32_toolchain//:core_lib"],
)

#cc_library(
#    name = "hello_lib",
#    srcs = ["hello.cc"],
#    copts = [
#      "-I/home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/cores/esp32",
#    ],
#    visibility = ["//visibility:public"],
#)

genrule(
    name = "gen_image",
    srcs = [":hello"],
    outs = ["hello.bin"],
    cmd = "python /home/simon/.arduino15/packages/esp32/tools/esptool_py/3.0.0/esptool.py --chip esp32 elf2image --flash_mode dio --flash_freq 80m --flash_size 4MB -o \"$@\" \"$<\"",
)

genrule(
    name = "gen_partitions",
    srcs = [],
    outs = ["hello.partitions.bin"],
    cmd = "python /home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/gen_esp32part.py /home/simon/.arduino15/packages/esp32/hardware/esp32/2.0.0-alpha1/tools/partitions/min_spiffs.csv \"$@\"",
)
