load(
    "@bazel_tools//tools/cpp:cc_toolchain_config_lib.bzl",
    "action_config",
    "artifact_name_pattern",
    "env_entry",
    "env_set",
    "feature",
    "feature_set",
    "flag_group",
    "flag_set",
    "make_variable",
    "tool",
    "tool_path",
    "variable_with_value",
    "with_feature_set",
)
load("@bazel_tools//tools/build_defs/cc:action_names.bzl", "ACTION_NAMES")

INCLUDE_FLAGS = [
    "-Iexternal/arduino_esp32/cores/esp32",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/config",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/newlib/platform_include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/freertos/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/freertos/port/xtensa/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_hw_support/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_hw_support/include/soc",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_hw_support/port/esp32",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/heap/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/log/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/lwip/include/apps",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/lwip/include/apps/sntp",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/lwip/lwip/src/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/lwip/port/esp32/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/lwip/port/esp32/include/arch",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/soc/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/soc/esp32",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/soc/esp32/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/hal/esp32/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/hal/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_rom/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_rom/esp32",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_common/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_system/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_system/port/soc",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_system/port/public_compat",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp32/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/driver/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/driver/esp32/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_pm/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_ringbuf/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/efuse/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/efuse/esp32/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/xtensa/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/xtensa/esp32/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/vfs/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_wifi/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_wifi/esp32/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_event/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_netif/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_eth/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/tcpip_adapter/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/app_trace/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_timer/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/mbedtls/port/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/mbedtls/mbedtls/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/mbedtls/esp_crt_bundle/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/app_update/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/spi_flash/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/bootloader_support/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_ipc/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/nvs_flash/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/pthread/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_gdbstub/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_gdbstub/xtensa",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_gdbstub/esp32",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/espcoredump/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/espcoredump/include/port/xtensa",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/wpa_supplicant/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/wpa_supplicant/port/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/wpa_supplicant/include/esp_supplicant",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/perfmon/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/asio/asio/asio/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/asio/port/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/bt/common/osi/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/bt/include/esp32/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/bt/host/bluedroid/api/include/api",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/cbor/port/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/unity/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/unity/unity/src",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/cmock/CMock/src",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/coap/port/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/coap/port/include/coap",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/coap/libcoap/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/coap/libcoap/include/coap2",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/console",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/nghttp/port/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/nghttp/nghttp2/lib/includes",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-tls",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-tls/esp-tls-crypto",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_adc_cal/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_hid/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/tcp_transport/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_http_client/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_http_server/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_https_ota/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/protobuf-c/protobuf-c",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/protocomm/include/common",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/protocomm/include/security",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/protocomm/include/transports",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/mdns/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_local_ctrl/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/sdmmc/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_serial_slave_link/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_websocket_client/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/expat/expat/expat/lib",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/expat/port/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/wear_levelling/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/fatfs/diskio",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/fatfs/vfs",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/fatfs/src",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/freemodbus/common/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/idf_test/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/idf_test/include/esp32",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/jsmn/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/json/cJSON",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/libsodium/libsodium/src/libsodium/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/libsodium/port_include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/mqtt/esp-mqtt/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/openssl/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/spiffs/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/ulp/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/wifi_provisioning/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/button/button/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/json_parser",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/json_parser/jsmn/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/json_generator",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_schedule/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_rainmaker/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/qrcode/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/ws2812_led",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_littlefs/src",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp_littlefs/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/dotprod/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/support/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/windows/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/windows/hann/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/windows/blackman/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/windows/blackman_harris/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/windows/blackman_nuttall/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/windows/nuttall/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/windows/flat_top/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/iir/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/fir/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/math/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/math/add/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/math/sub/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/math/mul/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/math/addc/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/math/mulc/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/math/sqrt/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/matrix/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/fft/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/dct/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/conv/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/common/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-face/face_detection/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-face/face_recognition/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-face/object_detection/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-face/image_util/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-face/pose_estimation/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp-face/lib/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp32-camera/driver/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/esp32-camera/conversions/include",
    "-Iexternal/arduino_esp32/tools/sdk/esp32/include/fb_gfx/include",
    "-Iexternal/arduino_esp32/cores/esp32",
    "-Iexternal/arduino_esp32/variants/esp32",
]

COMMON_FLAGS = [
    "-DHAVE_CONFIG_H",
    "-DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"",
    "-DUNITY_INCLUDE_CONFIG_H",
    "-DWITH_POSIX",
    "-D_GNU_SOURCE",
    "-DIDF_VER=\"v4.4-dev-960-gcf457d412\"",
    "-DESP_PLATFORM",
    "-mlongcalls",
    "-Wno-frame-address",
    "-ffunction-sections",
    "-fdata-sections",
    "-Wno-error=unused-function",
    "-Wno-error=unused-variable",
    "-Wno-error=deprecated-declarations",
    "-Wno-unused-parameter",
    "-Wno-sign-compare",
    "-ggdb",
    "-O2",
    "-fstack-protector",
    "-fstrict-volatile-bitfields",
    "-Wno-error=unused-but-set-variable",
    "-MMD",
    "-c",
    "-DF_CPU=240000000L",
    "-DARDUINO=10607",
    "-DARDUINO_ESP32_DEV",
    "-DARDUINO_ARCH_ESP32",
    "-DARDUINO_BOARD=\"ESP32_DEV\"",
    "-DARDUINO_VARIANT=\"esp32\"",
    "-DESP32",
    "-DCORE_DEBUG_LEVEL=0",
    "-DARDUINO_RUNNING_CORE=1",
    "-DARDUINO_EVENT_RUNNING_CORE=1",
    "-DARDUINO_SERIAL_PORT=0",
]

def _impl(ctx):
    tool_paths = [
        tool_path(
            name = "gcc",
            path = "cc_wrapper.sh",
        ),
        tool_path(
            name = "ld",
            path = "xtensa-esp32-elf-ld",
        ),
        tool_path(
            name = "ar",
            path = "xtensa-esp32-elf-ar",
        ),
        tool_path(
            name = "cpp",
            path = "/bin/false",
        ),
        tool_path(
            name = "gcov",
            path = "/bin/false",
        ),
        tool_path(
            name = "nm",
            path = "/bin/false",
        ),
        tool_path(
            name = "objdump",
            path = "/bin/false",
        ),
        tool_path(
            name = "strip",
            path = "/bin/false",
        ),
    ]

    default_compile_flags_feature = feature(
        name = "default_compile_flags",
        enabled = True,
        flag_sets = [
            flag_set(
                actions = [
                    ACTION_NAMES.assemble,
                    ACTION_NAMES.preprocess_assemble,
                    ACTION_NAMES.linkstamp_compile,
                    ACTION_NAMES.cpp_compile,
                    ACTION_NAMES.cpp_header_parsing,
                    ACTION_NAMES.cpp_module_compile,
                    ACTION_NAMES.cpp_module_codegen,
                    ACTION_NAMES.lto_backend,
                    ACTION_NAMES.clif_match,
                ],
                flag_groups = [
                    flag_group(
                        flags = [
                            "-DCOMPILING_AS_CPP_NOT_C",
                            "-std=gnu++11",
                            "-fexceptions",
                            "-fno-rtti",
                        ] + COMMON_FLAGS + INCLUDE_FLAGS,
                    ),
                ],
            ),
        ],
    )

    default_c_compile_flags_feature = feature(
        name = "default_c_compile_flags",
        enabled = True,
        flag_sets = [
            flag_set(
                actions = [
                    ACTION_NAMES.c_compile,
                ],
                flag_groups = [
                    flag_group(
                        flags = [
                            "-DCOMPILING_AS_C_NOT_CPP",
                            "-std=gnu99",
                            "-Wno-old-style-declaration",
                        ] + COMMON_FLAGS + INCLUDE_FLAGS,
                    ),
                ],
            ),
        ],
    )

    all_link_actions = [
        ACTION_NAMES.cpp_link_executable,
        ACTION_NAMES.cpp_link_dynamic_library,
        ACTION_NAMES.cpp_link_nodeps_dynamic_library,
    ]

    default_link_flags_feature = feature(
        name = "default_link_flags",
        enabled = True,
        flag_sets = [
            flag_set(
                actions = all_link_actions,
                flag_groups = [
                    flag_group(
                        flags = [
                            "-Lexternal/arduino_esp32/tools/sdk/esp32/lib",
                            "-Lexternal/arduino_esp32/tools/sdk/esp32/ld",
                            "-T",
                            "esp32.rom.ld",
                            "-T",
                            "esp32.rom.api.ld",
                            "-T",
                            "esp32.rom.libgcc.ld",
                            "-T",
                            "esp32.rom.newlib-data.ld",
                            "-T",
                            "esp32.rom.syscalls.ld",
                            "-T",
                            "esp32_out.ld",
                            "-T",
                            "esp32.project.ld",
                            "-T",
                            "esp32.peripherals.ld",
                            "-mlongcalls",
                            "-Wno-frame-address",
                            "-Wl,--cref",
                            "-Wl,--gc-sections",
                            "-fno-rtti",
                            "-fno-lto",
                            "-Wl,--wrap=mbedtls_mpi_exp_mod",
                            "-u",
                            "esp_app_desc",
                            "-u",
                            "pthread_include_pthread_impl",
                            "-u",
                            "pthread_include_pthread_cond_impl",
                            "-u",
                            "pthread_include_pthread_local_storage_impl",
                            "-u",
                            "ld_include_panic_highint_hdl",
                            "-u",
                            "start_app",
                            "-u",
                            "start_app_other_cores",
                            "-u",
                            "vfs_include_syscalls_impl",
                            "-u",
                            "call_user_start_cpu0",
                            "-Wl,--undefined=uxTopUsedPriority",
                            "-u",
                            "app_main",
                            "-u",
                            "newlib_include_heap_impl",
                            "-u",
                            "newlib_include_syscalls_impl",
                            "-u",
                            "newlib_include_pthread_impl",
                            "-u",
                            "__cxa_guard_dummy",
                            "-DESP32",
                            "-DCORE_DEBUG_LEVEL=0",
                            "-DARDUINO_RUNNING_CORE=1",
                            "-DARDUINO_EVENT_RUNNING_CORE=1",
                            "-DARDUINO_SERIAL_PORT=0",
                            "-Wl,--start-group",
                            "-lapp_trace",
                            "-lapp_update",
                            "-lasio",
                            "-lbootloader_support",
                            "-lbt",
                            "-lbtdm_app",
                            "-lbutton",
                            "-lc",
                            "-lcbor",
                            "-lcmock",
                            "-lcoap",
                            "-lcoexist",
                            "-lconsole",
                            "-lcore",
                            "-lcxx",
                            "-ldetection",
                            "-ldetection_cat_face",
                            "-ldl",
                            "-ldriver",
                            "-lefuse",
                            "-lesp32",
                            "-lesp32-camera",
                            "-lesp_adc_cal",
                            "-lesp_common",
                            "-lespcoredump",
                            "-lesp-dsp",
                            "-lesp_eth",
                            "-lesp_event",
                            "-lesp-face",
                            "-lesp_gdbstub",
                            "-lesp_hid",
                            "-lesp_http_client",
                            "-lesp_http_server",
                            "-lesp_https_ota",
                            "-lesp_hw_support",
                            "-lesp_ipc",
                            "-lesp_littlefs",
                            "-lesp_local_ctrl",
                            "-lesp_netif",
                            "-lespnow",
                            "-lesp_pm",
                            "-lesp_rainmaker",
                            "-lesp_ringbuf",
                            "-lesp_rom",
                            "-lesp_schedule",
                            "-lesp_serial_slave_link",
                            "-lesp_system",
                            "-lesp_timer",
                            "-lesp-tls",
                            "-lesp_websocket_client",
                            "-lesp_wifi",
                            "-lexpat",
                            "-lfatfs",
                            "-lfb_gfx",
                            "-lfd",
                            "-lfr",
                            "-lfreemodbus",
                            "-lfreertos",
                            "-lgcc",
                            "-lgcov",
                            "-lhal",
                            "-lheap",
                            "-ljsmn",
                            "-ljson",
                            "-ljson_generator",
                            "-ljson_parser",
                            "-llibsodium",
                            "-llog",
                            "-llwip",
                            "-lm",
                            "-lmbedcrypto",
                            "-lmbedtls",
                            "-lmbedx509",
                            "-lmdns",
                            "-lmesh",
                            "-lmqtt",
                            "-lnet80211",
                            "-lnewlib",
                            "-lnghttp",
                            "-lnvs_flash",
                            "-lopenssl",
                            "-lpe",
                            "-lperfmon",
                            "-lphy",
                            "-lpp",
                            "-lprotobuf-c",
                            "-lprotocomm",
                            "-lpthread",
                            "-lqrcode",
                            "-lrtc",
                            "-lsdmmc",
                            "-lsmartconfig",
                            "-lsoc",
                            "-lspiffs",
                            "-lspi_flash",
                            "-lstdc++",
                            "-ltcpip_adapter",
                            "-ltcp_transport",
                            "-lulp",
                            "-lunity",
                            "-lvfs",
                            "-lwapi",
                            "-lwear_levelling",
                            "-lwifi_provisioning",
                            "-lwpa_supplicant",
                            "-lws2812_led",
                            "-lxtensa",
                            "-lxt_hal",
                            "-Wl,--end-group",
                            "-Wl,-EL",
                        ],
                    ),
                ],
            ),
        ],
    )

    features = [
        default_compile_flags_feature,
        default_c_compile_flags_feature,
        default_link_flags_feature,
    ]

    return cc_common.create_cc_toolchain_config_info(
        ctx = ctx,
        cxx_builtin_include_directories = [
            "external/xtensa_esp32_elf_linux64/xtensa-esp32-elf/sys-include",
            "external/xtensa_esp32_elf_linux64/xtensa-esp32-elf/include/c++/8.4.0",
            "external/xtensa_esp32_elf_linux64/lib/gcc/xtensa-esp32-elf/8.4.0/include-fixed",
            "external/xtensa_esp32_elf_linux64/lib/gcc/xtensa-esp32-elf/8.4.0/include",
            "external/arduino_esp32/cores/esp32",
            "external/arduino_esp32/tools/sdk/esp32/include/config",
            "external/arduino_esp32/tools/sdk/esp32/include/newlib/platform_include",
            "external/arduino_esp32/tools/sdk/esp32/include/freertos/include",
            "external/arduino_esp32/tools/sdk/esp32/include/freertos/port/xtensa/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_hw_support/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_hw_support/include/soc",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_hw_support/port/esp32",
            "external/arduino_esp32/tools/sdk/esp32/include/heap/include",
            "external/arduino_esp32/tools/sdk/esp32/include/log/include",
            "external/arduino_esp32/tools/sdk/esp32/include/lwip/include/apps",
            "external/arduino_esp32/tools/sdk/esp32/include/lwip/include/apps/sntp",
            "external/arduino_esp32/tools/sdk/esp32/include/lwip/lwip/src/include",
            "external/arduino_esp32/tools/sdk/esp32/include/lwip/port/esp32/include",
            "external/arduino_esp32/tools/sdk/esp32/include/lwip/port/esp32/include/arch",
            "external/arduino_esp32/tools/sdk/esp32/include/soc/include",
            "external/arduino_esp32/tools/sdk/esp32/include/soc/esp32",
            "external/arduino_esp32/tools/sdk/esp32/include/soc/esp32/include",
            "external/arduino_esp32/tools/sdk/esp32/include/hal/esp32/include",
            "external/arduino_esp32/tools/sdk/esp32/include/hal/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_rom/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_rom/esp32",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_common/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_system/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_system/port/soc",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_system/port/public_compat",
            "external/arduino_esp32/tools/sdk/esp32/include/esp32/include",
            "external/arduino_esp32/tools/sdk/esp32/include/driver/include",
            "external/arduino_esp32/tools/sdk/esp32/include/driver/esp32/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_pm/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_ringbuf/include",
            "external/arduino_esp32/tools/sdk/esp32/include/efuse/include",
            "external/arduino_esp32/tools/sdk/esp32/include/efuse/esp32/include",
            "external/arduino_esp32/tools/sdk/esp32/include/xtensa/include",
            "external/arduino_esp32/tools/sdk/esp32/include/xtensa/esp32/include",
            "external/arduino_esp32/tools/sdk/esp32/include/vfs/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_wifi/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_wifi/esp32/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_event/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_netif/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_eth/include",
            "external/arduino_esp32/tools/sdk/esp32/include/tcpip_adapter/include",
            "external/arduino_esp32/tools/sdk/esp32/include/app_trace/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_timer/include",
            "external/arduino_esp32/tools/sdk/esp32/include/mbedtls/port/include",
            "external/arduino_esp32/tools/sdk/esp32/include/mbedtls/mbedtls/include",
            "external/arduino_esp32/tools/sdk/esp32/include/mbedtls/esp_crt_bundle/include",
            "external/arduino_esp32/tools/sdk/esp32/include/app_update/include",
            "external/arduino_esp32/tools/sdk/esp32/include/spi_flash/include",
            "external/arduino_esp32/tools/sdk/esp32/include/bootloader_support/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_ipc/include",
            "external/arduino_esp32/tools/sdk/esp32/include/nvs_flash/include",
            "external/arduino_esp32/tools/sdk/esp32/include/pthread/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_gdbstub/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_gdbstub/xtensa",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_gdbstub/esp32",
            "external/arduino_esp32/tools/sdk/esp32/include/espcoredump/include",
            "external/arduino_esp32/tools/sdk/esp32/include/espcoredump/include/port/xtensa",
            "external/arduino_esp32/tools/sdk/esp32/include/wpa_supplicant/include",
            "external/arduino_esp32/tools/sdk/esp32/include/wpa_supplicant/port/include",
            "external/arduino_esp32/tools/sdk/esp32/include/wpa_supplicant/include/esp_supplicant",
            "external/arduino_esp32/tools/sdk/esp32/include/perfmon/include",
            "external/arduino_esp32/tools/sdk/esp32/include/asio/asio/asio/include",
            "external/arduino_esp32/tools/sdk/esp32/include/asio/port/include",
            "external/arduino_esp32/tools/sdk/esp32/include/bt/common/osi/include",
            "external/arduino_esp32/tools/sdk/esp32/include/bt/include/esp32/include",
            "external/arduino_esp32/tools/sdk/esp32/include/bt/host/bluedroid/api/include/api",
            "external/arduino_esp32/tools/sdk/esp32/include/cbor/port/include",
            "external/arduino_esp32/tools/sdk/esp32/include/unity/include",
            "external/arduino_esp32/tools/sdk/esp32/include/unity/unity/src",
            "external/arduino_esp32/tools/sdk/esp32/include/cmock/CMock/src",
            "external/arduino_esp32/tools/sdk/esp32/include/coap/port/include",
            "external/arduino_esp32/tools/sdk/esp32/include/coap/port/include/coap",
            "external/arduino_esp32/tools/sdk/esp32/include/coap/libcoap/include",
            "external/arduino_esp32/tools/sdk/esp32/include/coap/libcoap/include/coap2",
            "external/arduino_esp32/tools/sdk/esp32/include/console",
            "external/arduino_esp32/tools/sdk/esp32/include/nghttp/port/include",
            "external/arduino_esp32/tools/sdk/esp32/include/nghttp/nghttp2/lib/includes",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-tls",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-tls/esp-tls-crypto",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_adc_cal/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_hid/include",
            "external/arduino_esp32/tools/sdk/esp32/include/tcp_transport/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_http_client/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_http_server/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_https_ota/include",
            "external/arduino_esp32/tools/sdk/esp32/include/protobuf-c/protobuf-c",
            "external/arduino_esp32/tools/sdk/esp32/include/protocomm/include/common",
            "external/arduino_esp32/tools/sdk/esp32/include/protocomm/include/security",
            "external/arduino_esp32/tools/sdk/esp32/include/protocomm/include/transports",
            "external/arduino_esp32/tools/sdk/esp32/include/mdns/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_local_ctrl/include",
            "external/arduino_esp32/tools/sdk/esp32/include/sdmmc/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_serial_slave_link/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_websocket_client/include",
            "external/arduino_esp32/tools/sdk/esp32/include/expat/expat/expat/lib",
            "external/arduino_esp32/tools/sdk/esp32/include/expat/port/include",
            "external/arduino_esp32/tools/sdk/esp32/include/wear_levelling/include",
            "external/arduino_esp32/tools/sdk/esp32/include/fatfs/diskio",
            "external/arduino_esp32/tools/sdk/esp32/include/fatfs/vfs",
            "external/arduino_esp32/tools/sdk/esp32/include/fatfs/src",
            "external/arduino_esp32/tools/sdk/esp32/include/freemodbus/common/include",
            "external/arduino_esp32/tools/sdk/esp32/include/idf_test/include",
            "external/arduino_esp32/tools/sdk/esp32/include/idf_test/include/esp32",
            "external/arduino_esp32/tools/sdk/esp32/include/jsmn/include",
            "external/arduino_esp32/tools/sdk/esp32/include/json/cJSON",
            "external/arduino_esp32/tools/sdk/esp32/include/libsodium/libsodium/src/libsodium/include",
            "external/arduino_esp32/tools/sdk/esp32/include/libsodium/port_include",
            "external/arduino_esp32/tools/sdk/esp32/include/mqtt/esp-mqtt/include",
            "external/arduino_esp32/tools/sdk/esp32/include/openssl/include",
            "external/arduino_esp32/tools/sdk/esp32/include/spiffs/include",
            "external/arduino_esp32/tools/sdk/esp32/include/ulp/include",
            "external/arduino_esp32/tools/sdk/esp32/include/wifi_provisioning/include",
            "external/arduino_esp32/tools/sdk/esp32/include/button/button/include",
            "external/arduino_esp32/tools/sdk/esp32/include/json_parser",
            "external/arduino_esp32/tools/sdk/esp32/include/json_parser/jsmn/include",
            "external/arduino_esp32/tools/sdk/esp32/include/json_generator",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_schedule/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_rainmaker/include",
            "external/arduino_esp32/tools/sdk/esp32/include/qrcode/include",
            "external/arduino_esp32/tools/sdk/esp32/include/ws2812_led",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_littlefs/src",
            "external/arduino_esp32/tools/sdk/esp32/include/esp_littlefs/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/dotprod/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/support/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/windows/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/windows/hann/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/windows/blackman/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/windows/blackman_harris/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/windows/blackman_nuttall/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/windows/nuttall/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/windows/flat_top/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/iir/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/fir/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/math/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/math/add/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/math/sub/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/math/mul/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/math/addc/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/math/mulc/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/math/sqrt/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/matrix/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/fft/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/dct/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/conv/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-dsp/modules/common/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-face/face_detection/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-face/face_recognition/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-face/object_detection/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-face/image_util/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-face/pose_estimation/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp-face/lib/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp32-camera/driver/include",
            "external/arduino_esp32/tools/sdk/esp32/include/esp32-camera/conversions/include",
            "external/arduino_esp32/tools/sdk/esp32/include/fb_gfx/include",
            "external/arduino_esp32/cores/esp32",
            "external/arduino_esp32/variants/esp32",
        ],
        features = features,
        toolchain_identifier = "xtensa-toolchain",
        host_system_name = "local",
        target_system_name = "local",
        target_cpu = "xtensa",
        target_libc = "unknown",
        compiler = "cpp",
        abi_version = "unknown",
        abi_libc_version = "unknown",
        tool_paths = tool_paths,
    )

cc_toolchain_config = rule(
    implementation = _impl,
    attrs = {},
    provides = [CcToolchainConfigInfo],
)
